version: "3.7"

services:
  redis:
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
  web:
    build: "."
    command: bundle exec rake
    ports:
      - "3000:3000"
    build:
      context: ./
      args:
        RAILS_ENV: test
    links:
      - redis
    env_file:
       - .env.test
    volumes:
      - .:/srv/app
